# Generated by Django 5.2.13 on 2026-04-24 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('place_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('low', 'Low Gas'), ('no_gas', 'No Gas'), ('closed', 'Closed')], default='available', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('opening_hours', models.TextField(blank=True, help_text='JSON formatted opening hours', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CNG Station',
                'verbose_name_plural': 'CNG Stations',
                'db_table': 'stations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QueueUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_length', models.PositiveIntegerField(help_text='Estimated number of vehicles in queue')),
                ('availability', models.CharField(choices=[('available', 'Gas Available'), ('low', 'Low Gas'), ('no_gas', 'No Gas')], default='available', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_updates', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_updates', to='stations.station')),
            ],
            options={
                'verbose_name': 'Queue Update',
                'verbose_name_plural': 'Queue Updates',
                'db_table': 'queue_updates',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QueueVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='stations.queueupdate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'queue_votes',
                'unique_together': {('update', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='stations.station')),
            ],
            options={
                'db_table': 'favorites',
                'unique_together': {('user', 'station')},
            },
        ),
    ]
