# Generated by Django 5.2.13 on 2026-04-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='queue_time',
            field=models.IntegerField(default=0, help_text='Queue time in minutes'),
        ),
    ]
